name: "PHPCS"

on:
  pull_request:
    paths:
      - "**.php"
      - ".github/workflows/phpcs.yaml"
    branches-ignore:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Install PHP_CodeSniffer
        run: |
          curl -L https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/latest/download/phpcs.phar -o phpcs.phar
          php phpcs.phar --version

      - name: Get our latest coding standards
        run: |
          curl -L https://raw.githubusercontent.com/xibosignage/support/refs/heads/php8/src/Standards/xibo_ruleset.xml -o xibo_ruleset.xml

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: php ${{ github.workspace }}/phpcs.phar
          standard: ${{ github.workspace }}/xibo_ruleset.xml